diffy:
  image: camiloribeiro/twitter-diffy
  ports:
    - "8888:8888"
    - "31900:31900"
  links:
    - primary 
    - secondary
    - candidate
  command: java -jar ./target/scala-2.11/diffy-server.jar -candidate='candidate:8080' -master.primary='primary:8080' -master.secondary='secondary:8080' -service.protocol='http' -serviceName='Happy Service' -proxy.port=:31900 -admin.port=:8881 -http.port=:8888 -rootUrl='localhost:8888'

candidate:
  image: camiloribeiro/rest_shifter
  ports:
    - "9881:8080"
  volumes:
    - flavors/candidate:/root/.rest_shifter/flavors
  command: -s

primary:
  image: camiloribeiro/rest_shifter
  ports:
    - "9882:8080"
  volumes:
    - flavors/primary:/root/.rest_shifter/flavors
  command: -s

secondary:
  image: camiloribeiro/rest_shifter
  ports:
    - "9883:8080"
  volumes:
    - flavors/secondary:/root/.rest_shifter/flavors
  command: -s
